@FooService_HostAddress = http://localhost:5053

GET {{FooService_HostAddress}}/foos/
Accept: application/json

###

GET {{FooService_HostAddress}}/foos/1
Accept: application/json

###

DELETE {{FooService_HostAddress}}/foos/1
Accept: application/json

###
